### ISSUE TITLE
Display episode author on homepage and in episode archive

### ISSUE THREAD

**Issue by cwillems** [openHPI/PodcastGenerator#1]
See attached screenshot for design mockup
![Bildschirmfoto 2019-03-21 um 16 14 17](https://user-images.githubusercontent.com/1996660/54762624-bc041b80-4bf4-11e9-9ab9-c45b734c6c59.png)

**Comment by MatthiasWiesner** [comment]
Did it, but it doesn't look like expected. The container width is `width: 570px;`. If the title is long and you have many authors, then it will break:
![podcast_author](https://user-images.githubusercontent.com/871238/54769775-3a1aef00-4c02-11e9-99b4-4e648bcbc458.png)

**Comment by MatthiasWiesner** [comment]
Deactivated 'til a proper solution

**Comment by MatthiasWiesner** [comment]
My five cents:

![podcast_author_2](https://user-images.githubusercontent.com/871238/54770445-861a6380-4c03-11e9-9ab3-cf11b017a3c6.png)
